export const ADD_USER_TO_STORE = "USER.ADD_USER_TO_STORE"

export const ADD_PRODUCT_TO_STORE = "PRODUCT.ADD_PRODUCT_TO_STORE"

export const ADD_ERROR_TO_STORE = "ERROR.ADD_ERROR_TO_STORE"

export const ADD_ITEM_TO_CART = "CART.ADD_ITEM_TO_CART";
export const REMOVE_ITEM_FROM_CART = "CART.REMOVE_ITEM_FROM_CART";
export const UPDATE_ITEM_IN_CART = "CART.UPDATE_ITEM_IN_CART";
export const EMPTY_CART = "CART.EMPTY_CART";

export const ADD_ORDER_TO_STORE = "ORDER.ADD_ORDER_TO_STORE"
export const ADD_USERID_TO_STORE = "ORDER.ADD_USERID_TO_STORE"
export const ADD_ORDERID_TO_STORE = "ORDER.ADD_ORDERID_TO_STORE"
export const ADD_RECENT_ORDERS_TO_STORE = "ORDER.ADD_RECENT_ORDERS_TO_STORE"
export const ADD_CANCELLED_ORDERS_TO_STORE = "ORDER.ADD_CANCELLED_ORDERS_TO_STORE"
export const CANCEL_ORDER = "ORDER.CANCEL_ORDER"

export const CLEAR_ORDER_STORE = "ORDER.CLEAR_ORDER_STORE"