export const ADD_USER_TO_STORE = "USER.ADD_USER_TO_STORE"

export const ADD_PRODUCT_TO_STORE = "PRODUCT.ADD_PRODUCT_TO_STORE"

export const ADD_ERROR_TO_STORE = "ERROR.ADD_ERROR_TO_STORE"

export const ADD_ITEM_TO_CART = "CART.ADD_ITEM_TO_CART";
export const REMOVE_ITEM_FROM_CART = "CART.REMOVE_ITEM_FROM_CART";
export const UPDATE_ITEM_IN_CART = "CART.UPDATE_ITEM_IN_CART";
export const EMPTY_CART = "CART.EMPTY_CART";